application/models/__init__.py
from ._base import db
from .user import *
from .channel import *
from .piece import *

application/models/_base.py
from flask.ext.sqlalchemy import SQLAlchemy

db = SQLAlchemy()

application/forms/__init__.py
from .account import *
from .user import *
from .channel import *
from .piece import *

application/forms/_helper.py
# coding: utf-8
import re
from urlparse import urlparse


def check_url(form, field):
    """Check url schema."""
    url = field.data.strip()
    if not url:
        return
    result = urlparse(url)
    if result.scheme == "":
        field.data = "http://%s" % re.sub(r'^:?/*', '', url)

application/forms/account.py
# coding: utf-8
from flask_wtf import Form
from wtforms import StringField, PasswordField
from wtforms.validators import DataRequired, Email, EqualTo
from ..models import User


class SigninForm(Form):
    """Form for signin"""
    email = StringField('邮箱',
                        validators=[
                            DataRequired("邮箱不能为空"),
                            Email('邮箱格式错误')
                        ])

    password = PasswordField('密码',
                             validators=[DataRequired("密码不能为空")])

    def validate_email(self, field):
        user = User.query.filter(User.email == self.email.data).first()
        if not user:
            raise ValueError("账户不存在")

    def validate_password(self, field):
        if self.email.data:
            user = User.query.filter(User.email == self.email.data).first()
            if not user or not user.check_password(self.password.data):
                raise ValueError('密码错误')
            else:
                self.user = user


class SignupForm(Form):
    """Form for signin"""
    name = StringField('用户名',
                       validators=[DataRequired("用户名不能为空")])

    email = StringField('邮箱',
                        validators=[
                            DataRequired(message="邮箱不能为空"),
                            Email(message='邮箱格式错误')
                        ])

    password = PasswordField('密码',
                             validators=[DataRequired("密码不能为空")])

    def validate_name(self, field):
        user = User.query.filter(User.name == self.name.data).first()
        if user:
            raise ValueError('用户名已存在')

    def validate_email(self, field):
        user = User.query.filter(User.email == self.email.data).first()
        if user:
            raise ValueError('邮箱已存在')

application/forms/channel.py
# coding: utf-8
from flask_wtf import Form
from wtforms import StringField, HiddenField
from wtforms.validators import DataRequired


class ChannelForm(Form):
    name = StringField('名称', validators=[DataRequired('名称不能为空')])
    # cover = HiddenField('', validators=[DataRequired('图标不能为空')])
    # tags = StringField('标签')

application/forms/piece.py
# coding: utf-8
from flask_wtf import Form
from wtforms import StringField, TextAreaField, SelectField, HiddenField
from wtforms.validators import DataRequired, Optional


class TextForm(Form):
    channel_id = SelectField('频道', coerce=int)
    title = StringField('标题', validators=[Optional()], description='选填')
    content = TextAreaField('内容', validators=[DataRequired('内容不能为空')])


class ImageForm(Form):
    channel_id = SelectField('频道', coerce=int)
    image = HiddenField('图片', validators=[DataRequired('图片不能为空')])
    desc = TextAreaField('描述', validators=[Optional()])

application/forms/user.py
# coding: utf-8
from flask_wtf import Form
from wtforms import StringField
from wtforms.validators import DataRequired


class ExampleForm(Form):
    field = StringField('', validators=[DataRequired()])

application/__init__.py
# coding: utf-8
import sys
import os

# Insert project root path to sys.path
project_path = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
if project_path not in sys.path:
    sys.path.insert(0, project_path)

import time
import logging
from flask import Flask, request, url_for, g, render_template
from flask_wtf.csrf import CsrfProtect
from flask.ext.uploads import configure_uploads
from flask_debugtoolbar import DebugToolbarExtension
from werkzeug.wsgi import SharedDataMiddleware
from werkzeug.contrib.fixers import ProxyFix
from six import iteritems
from .utils.account import get_current_user
from config import load_config

# convert python's encoding to utf8
try:
    from imp import reload

    reload(sys)
    sys.setdefaultencoding('utf8')
except (AttributeError, NameError):
    pass


def create_app():
    """Create Flask app."""
    config = load_config()

    if config.DEBUG or config.TESTING:
        app = Flask(__name__)
    else:
        app = Flask(__name__, template_folder=os.path.join(project_path, 'output/templates'))

    app.config.from_object(config)

    if not hasattr(app, 'production'):
        app.production = not app.debug and not app.testing

    # Proxy fix
    app.wsgi_app = ProxyFix(app.wsgi_app)

    # CSRF protect
    CsrfProtect(app)

    # Log errors to stderr in production mode
    if app.production:
        app.logger.addHandler(logging.StreamHandler())
        app.logger.setLevel(logging.ERROR)

        # Enable Sentry
        if app.config.get('SENTRY_DSN'):
            from .utils.sentry import sentry

            sentry.init_app(app, dsn=app.config.get('SENTRY_DSN'))

        # Serve static files during production
        app.wsgi_app = SharedDataMiddleware(app.wsgi_app, {
            '/': os.path.join(project_path, 'output')
        })
    else:
        DebugToolbarExtension(app)

        # Serve static files during development
        app.wsgi_app = SharedDataMiddleware(app.wsgi_app, {
            '/uploads': os.path.join(app.config.get('PROJECT_PATH'), 'uploads')
        })

    # Register components
    register_db(app)
    register_routes(app)
    register_jinja(app)
    register_error_handle(app)
    register_uploadsets(app)
    register_hooks(app)

    return app


def register_jinja(app):
    """Register jinja filters, vars, functions."""
    from .utils import filters, permissions, helpers

    app.jinja_env.filters.update({
        'timesince': filters.timesince
    })

    def url_for_other_page(page):
        """Generate url for pagination."""
        view_args = request.view_args.copy()
        args = request.args.copy().to_dict()
        combined_args = dict(view_args.items() + args.items())
        combined_args['page'] = page
        return url_for(request.endpoint, **combined_args)

    rules = {}
    for endpoint, _rules in iteritems(app.url_map._rules_by_endpoint):
        if any(item in endpoint for item in ['_debug_toolbar', 'debugtoolbar', 'static']):
            continue
        rules[endpoint] = [{'rule': rule.rule} for rule in _rules]

    app.jinja_env.globals.update({
        'absolute_url_for': helpers.absolute_url_for,
        'url_for_other_page': url_for_other_page,
        'rules': rules,
        'permissions': permissions
    })


def register_db(app):
    """Register models."""
    from .models import db

    db.init_app(app)


def register_routes(app):
    """Register routes."""
    from . import controllers
    from flask.blueprints import Blueprint

    for module in _import_submodules_from_package(controllers):
        bp = getattr(module, 'bp')
        if bp and isinstance(bp, Blueprint):
            app.register_blueprint(bp)


def register_error_handle(app):
    """Register HTTP error pages."""

    @app.errorhandler(403)
    def page_403(error):
        return render_template('site/403.html'), 403

    @app.errorhandler(404)
    def page_404(error):
        return render_template('site/404.html'), 404

    @app.errorhandler(500)
    def page_500(error):
        return render_template('site/500.html'), 500


def register_uploadsets(app):
    """Register UploadSets."""
    from .utils.uploadsets import avatars, images

    configure_uploads(app, (avatars, images))


def register_hooks(app):
    """Register hooks."""

    @app.before_request
    def before_request():
        g.user = get_current_user()
        if g.user and g.user.is_admin:
            g._before_request_time = time.time()

    @app.after_request
    def after_request(response):
        if hasattr(g, '_before_request_time'):
            delta = time.time() - g._before_request_time
            response.headers['X-Render-Time'] = delta * 1000
        return response


def _get_template_name(template_reference):
    """Get current template name."""
    return template_reference._TemplateReference__context.name


def _import_submodules_from_package(package):
    import pkgutil

    modules = []
    for importer, modname, ispkg in pkgutil.iter_modules(package.__path__,
                                                         prefix=package.__name__ + "."):
        modules.append(__import__(modname, fromlist="dummy"))
    return modules

application/controllers/account.py
# coding: utf-8
from flask import render_template, Blueprint, redirect, request, url_for
from ..forms import SigninForm, SignupForm
from ..utils.account import signin_user, signout_user
from ..utils.permissions import VisitorPermission, UserPermission
from ..models import db, User

bp = Blueprint('account', __name__)


@bp.route('/signin', methods=['GET', 'POST'])
@VisitorPermission()
def signin():
    """Signin"""
    form = SigninForm()
    if form.validate_on_submit():
        signin_user(form.user)
        return redirect(url_for('site.index'))
    return render_template('account/signin.html', form=form)


@bp.route('/signup', methods=['GET', 'POST'])
@VisitorPermission()
def signup():
    """Signup"""
    form = SignupForm()
    if form.validate_on_submit():
        user = User(**form.data)
        db.session.add(user)
        db.session.commit()
        signin_user(user)
        return redirect(url_for('site.index'))
    return render_template('account/signup.html', form=form)


@bp.route('/signout')
def signout():
    """Signout"""
    signout_user()
    return redirect(request.referrer or url_for('site.index'))

application/controllers/channel.py
# coding: utf-8
from flask import Blueprint, render_template, redirect, url_for, g, request
from ..utils.permissions import UserPermission
from ..forms.channel import ChannelForm
from ..models import db, Channel, Piece
from ..utils.decorators import jsonify
from ..utils.uploadsets import images, process_channel_cover

bp = Blueprint('channel', __name__)


@bp.route('/channel/add', methods=['GET', 'POST'])
@UserPermission()
def add():
    """创建频道"""
    form = ChannelForm()
    if form.validate_on_submit():
        channel = Channel(name=form.name.data, user_id=g.user.id)
        db.session.add(channel)
        db.session.commit()
        return redirect(url_for('.view', uid=channel.id))
    return render_template('channel/add.html', form=form)


@bp.route('/channel/remove', methods=['POST'])
@UserPermission()
def remove():
    """移除频道"""
    pass


@bp.route('/channel/<int:uid>/edit', methods=['GET', 'POST'])
@UserPermission()
def edit(uid):
    """编辑频道"""
    channel = Channel.query.get_or_404(uid)
    form = ChannelForm(obj=channel)
    if form.validate_on_submit():
        # channel.cover = form.cover.data
        channel.name = form.name.data
        db.session.add(channel)
        db.session.commit()
        return redirect(url_for('.view', uid=channel.id))
    return render_template('channel/edit.html', form=form, channel=channel)


@bp.route('/channel/<int:uid>')
def view(uid):
    """频道主页"""
    channel = Channel.query.get_or_404(uid)
    pieces = channel.pieces
    return render_template('channel/view.html', channel=channel, pieces=pieces)


@bp.route('/channel/upload_cover', methods=['POST'])
@UserPermission()
@jsonify
def upload_cover():
    """上传通用图片"""
    try:
        filename = process_channel_cover(request.files['file'])
    except Exception, e:
        return {'result': False, 'error': e.__repr__()}
    else:
        return {'result': True, 'url': images.url(filename), 'path': filename}

application/controllers/piece.py
# coding: utf-8
from flask import Blueprint, render_template, redirect, url_for, g, request
from ..utils.permissions import UserPermission
from ..forms.piece import TextForm, ImageForm
from ..models import db, Piece

bp = Blueprint('piece', __name__)


@bp.route('/piece/add')
@UserPermission()
def add():
    """添加条目"""
    return render_template('piece/add.html')


@bp.route('/piece/add_text', methods=['GET', 'POST'])
@UserPermission()
def add_text():
    """添加文字类条目"""
    channel_id = request.args.get('channel_id', type=int)
    form = TextForm()
    if channel_id:
        form.channel_id.data = channel_id
    form.channel_id.choices = [(c.id, c.name) for c in g.user.channels]
    if form.validate_on_submit():
        piece = Piece(title=form.title.data, content=form.content.data, channel_id=form.channel_id.data,
                      user_id=g.user.id, kind='TEXT')
        db.session.add(piece)
        db.session.commit()
        return redirect(url_for('channel.view', uid=piece.channel_id))
    return render_template('piece/add_text.html', form=form)


@bp.route('/piece/edit_text')
def edit_text():
    """编辑文字类条目"""
    return render_template('piece/edit_text.html')


@bp.route('/piece/add_image', methods=['GET', 'POST'])
@UserPermission()
def add_image():
    """添加图片"""
    channel_id = request.args.get('channel_id', type=int)
    form = ImageForm()
    if channel_id:
        form.channel_id.data = channel_id
    form.channel_id.choices = [(c.id, c.name) for c in g.user.channels]
    if form.validate_on_submit():
        piece = Piece(image=form.image.data, desc=form.desc.data, channel_id=form.channel_id.data, user_id=g.user.id,
                      kind='IMAGE')
        db.session.add(piece)
        db.session.commit()
        return redirect(url_for('channel.view', uid=piece.channel_id))
    return render_template('piece/add_image.html', form=form)


@bp.route('/piece/edit_image')
def edit_image():
    return render_template('piece/edit_image.html')


@bp.route('/piece/<int:uid>')
def view(uid):
    """单个条目"""
    piece = Piece.query.get_or_404(uid)
    return render_template('piece/view.html', piece=piece)


@bp.route('/piece/<int:uid>/edit', methods=['GET', 'POST'])
@UserPermission()
def edit(uid):
    """编辑条目"""
    piece = Piece.query.get_or_404(uid)
    if piece.kind == 'TEXT':
        form = TextForm(obj=piece)
        form.channel_id.choices = [(c.id, c.name) for c in g.user.channels]
        if form.validate_on_submit():
            piece.title = form.title.data
            piece.content = form.content.data
            piece.channel_id = form.channel_id.data
            db.session.add(piece)
            db.session.commit()
            return redirect(url_for('.view', uid=uid))
        return render_template('piece/edit_text.html', form=form)

    elif piece.kind == 'IMAGE':
        form = ImageForm(obj=piece)
        form.channel_id.choices = [(c.id, c.name) for c in g.user.channels]
        if form.validate_on_submit():
            piece.image = form.image.data
            piece.desc = form.desc.data
            piece.channel_id = form.channel_id.data
            db.session.add(piece)
            db.session.commit()
            return redirect(url_for('.view', uid=uid))
        return render_template('piece/edit_image.html', form=form)

application/controllers/site.py
# coding: utf-8
from flask import render_template, Blueprint, request, redirect, url_for, g
from ..utils.permissions import UserPermission
from ..utils.decorators import jsonify
from ..utils.uploadsets import images, process_site_image
from ..models import Channel

bp = Blueprint('site', __name__)


@bp.route('/')
def index():
    """Index page."""
    if not g.user:
        return redirect(url_for('.discover'))
    return render_template('site/index.html')


@bp.route('/about')
def about():
    """About page."""
    return render_template('site/about.html')


@bp.route('/upload_image', methods=['POST'])
@UserPermission()
@jsonify
def upload_image():
    """上传通用图片"""
    try:
        filename = process_site_image(request.files['file'])
    except Exception, e:
        return {'success': False, 'error': e.__repr__()}
    else:
        return {'success': True, 'file_path': images.url(filename)}


@bp.route('/discover')
def discover():
    """发现"""
    channels = Channel.query.limit(30)
    return render_template('site/discover.html', channels=channels)

application/controllers/user.py
# coding: utf-8
from flask import Blueprint, render_template, g
from ..models import Channel, User
from ..utils.permissions import UserPermission

bp = Blueprint('user', __name__)


@bp.route('/my/channels')
@UserPermission()
def channels():
    """我的频道"""
    channels = g.user.channels
    return render_template('user/channels.html', channels=channels)


@bp.route('/people/<int:uid>')
def profile(uid):
    """用户主页"""
    user = User.query.get_or_404(uid)
    channels = user.channels
    return render_template('user/profile.html', user=user, channels=channels)


@bp.route('/people/<int:uid>/channels')
def channels_for_profile(uid):
    """用户频道"""
    user = User.query.get_or_404(uid)
    channels = user.channels
    return render_template('user/channels_for_profile.html', user=user, channels=channels)

application/templates/layout.html
<!doctype html>
<html>
<head>
    <title>{% block page_title %}{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="csrf-token" content="{{ csrf_token() }}"/>
    {% block meta %}{% endblock %}
    <link rel="Shortcut Icon" href="/static/image/favicon.png">
    {# CSS libs #}
    <link rel="stylesheet" href="/static/css/libs/bootstrap.css"/>
    <link rel="stylesheet" href="/static/css/libs/font-awesome.css"/>
    <link rel="stylesheet" href="/static/css/libs/simditor.css"/>
    <link rel="stylesheet" href="/static/css/libs/simditor-markdown.css"/>
    <link rel="stylesheet" href="/static/css/libs/highlightjs.css">
    {# CSS layout #}
    <link rel="stylesheet" href="/static/css/bootstrap.theme.css"/>
    <link rel="stylesheet" href="/static/css/common.css"/>
    <link rel="stylesheet" href="/static/css/macros/_user.css"/>
    <link rel="stylesheet" href="/static/css/macros/_channel.css">
    <link rel="stylesheet" href="/static/css/macros/_piece.css">
    <link rel="stylesheet" href="/static/css/layout.css"/>
    {# CSS page #}
    {% block page_css %}{% endblock %}
    {# JS global vars #}
    <script type="text/javascript">
        var g = {
            domain: "{{ config.SITE_DOMAIN }}",
            csrfToken: "{{ csrf_token() }}",
            rules: {{ rules|safe }},
            method: "{{ request.method }}",
            signin: {% if g.user %}true{% else %}false{% endif %},
            userId: {% if g.user %}{{ g.user.id }}{% else %}false{% endif %}
        };
    </script>
    {# JS libs #}
    <script src="/static/js/libs/respond.min.js"></script>
    <script src="/static/js/libs/jquery.min.js"></script>
    <script src="/static/js/libs/bootstrap.min.js"></script>
    <script src="/static/js/libs/module.js"></script>
    <script src="/static/js/libs/hotkeys.js"></script>
    <script src="/static/js/libs/uploader.js"></script>
    <script src="/static/js/libs/simditor.js"></script>
    <script src="/static/js/libs/marked.min.js"></script>
    <script src="/static/js/libs/to-markdown.js"></script>
    <script src="/static/js/libs/simditor-markdown.js"></script>
    <script src="/static/js/libs/highlight.pack.js"></script>
    <script src="/static/js/init.js"></script>
</head>

<body>

{# Flash message #}
{% with message = get_flashed_messages()[0] %}
    {% if message %}
        <div class="alert alert-info flash-message">{{ message }}</div>
    {% endif %}
{% endwith %}

<nav class="navbar navbar-default navbar-static-top">
    <div class="navbar-header">
        <a class="navbar-brand" href="{{ url_for('site.index') }}">
            面面
        </a>
    </div>

    <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
            {#            <li id="nav-index">#}
            {#                <a href="{{ url_for('site.index') }}">首页</a>#}
            {#            </li>#}
            {#                <li id="nav-about">#}
            {#                    <a href="{{ url_for('site.about') }}">关于</a>#}
            {#                </li>#}
        </ul>

        {#            <form class="navbar-form navbar-left" role="search" method="get" action="#">#}
        {#                <div class="input-group">#}
        {#                    <input type="text" name="keyword" class="form-control input-sm"#}
        {#                           placeholder="">#}
        {#               <span class="input-group-btn">#}
        {#                  <button class="btn btn-default btn-sm" type="submit">#}
        {#                      <span class="fa fa-search"></span>#}
        {#                  </button>#}
        {#               </span>#}
        {#                </div>#}
        {#            </form>#}

        <ul class="nav navbar-nav navbar-right">
            {% if g.user %}
                {#                <li class="">#}
                {#                    <a href="{{ url_for('piece.add_text') }}">#}
                {#                        <span class="fa fa-pencil"></span></a>#}
                {#                </li>#}
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                       aria-expanded="false">
                        <span class="fa fa-pencil"></span> <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li><a href="{{ url_for('piece.add_text') }}"><span class="fa fa-font"></span> 文字</a></li>
                        <li><a href="{{ url_for('piece.add_image') }}"><span class="fa fa-camera"></span> 图片</a></li>
                    </ul>
                </li>

                <li>
                    <a href="{{ url_for('site.discover') }}">发现</a>
                </li>

                <li>
                    <a href="{{ url_for('user.channels') }}">我的频道</a>
                </li>

                <li id="nav-settings" class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        {{ g.user.name }} <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="{{ url_for('user.profile', uid=g.user.id) }}">个人主页</a></li>
                        <li><a href="#">我关注的频道</a></li>
                        <li><a href="#">设置</a></li>
                        <li><a href="{{ url_for('account.signout') }}">登出</a></li>
                    </ul>
                </li>
            {% else %}
                <li id="nav-signin">
                    <a href="{{ url_for('account.signin') }}">登陆</a>
                </li>
                <li id="nav-signup">
                    <a href="{{ url_for('account.signup') }}">注册</a>
                </li>
            {% endif %}
        </ul>
    </div>
</nav>

<div id="main-wap">
    {% block page_content %}{% endblock %}
</div>

{#<div id="footer">#}
{#    <div class='container'>#}
{#        <div id='copyright' class="pull-left">#}
{#            © 2015 面面#}
{#        </div>#}
{##}
{#        <ul id='links' class="pull-right list-unstyled list-inline">#}
{#            <li><a href="{{ url_for('site.about') }}">关于</a></li>#}
{#        </ul>#}
{#    </div>#}
{#</div>#}

{# JS layout #}
<script src="/static/js/layout.js"></script>

{# JS page #}
{% block page_js %}{% endblock %}

</body>
</html>