application/models/__init__.py
from ._base import db
from .user import *
from .channel import *
from .piece import *

application/models/_base.py
from flask.ext.sqlalchemy import SQLAlchemy

db = SQLAlchemy()

application/forms/__init__.py
from .account import *
from .user import *
from .channel import *
from .piece import *

application/forms/_helper.py
# coding: utf-8
import re
from urlparse import urlparse


def check_url(form, field):
    """Check url schema."""
    url = field.data.strip()
    if not url:
        return
    result = urlparse(url)
    if result.scheme == "":
        field.data = "http://%s" % re.sub(r'^:?/*', '', url)

application/forms/account.py
# coding: utf-8
from flask_wtf import Form
from wtforms import StringField, PasswordField
from wtforms.validators import DataRequired, Email, EqualTo
from ..models import User


class SigninForm(Form):
    """Form for signin"""
    email = StringField('邮箱',
                        validators=[
                            DataRequired("邮箱不能为空"),
                            Email('邮箱格式错误')
                        ])

    password = PasswordField('密码',
                             validators=[DataRequired("密码不能为空")])

    def validate_email(self, field):
        user = User.query.filter(User.email == self.email.data).first()
        if not user:
            raise ValueError("账户不存在")

    def validate_password(self, field):
        if self.email.data:
            user = User.query.filter(User.email == self.email.data).first()
            if not user or not user.check_password(self.password.data):
                raise ValueError('密码错误')
            else:
                self.user = user


class SignupForm(Form):
    """Form for signin"""
    name = StringField('用户名',
                       validators=[DataRequired("用户名不能为空")])

    email = StringField('邮箱',
                        validators=[
                            DataRequired(message="邮箱不能为空"),
                            Email(message='邮箱格式错误')
                        ])

    password = PasswordField('密码',
                             validators=[DataRequired("密码不能为空")])

    def validate_name(self, field):
        user = User.query.filter(User.name == self.name.data).first()
        if user:
            raise ValueError('用户名已存在')

    def validate_email(self, field):
        user = User.query.filter(User.email == self.email.data).first()
        if user:
            raise ValueError('邮箱已存在')

application/forms/channel.py
# coding: utf-8
from flask_wtf import Form
from wtforms import StringField, HiddenField
from wtforms.validators import DataRequired


class ChannelForm(Form):
    name = StringField('名称', validators=[DataRequired('名称不能为空')])
    # cover = HiddenField('', validators=[DataRequired('图标不能为空')])
    # tags = StringField('标签')

application/forms/piece.py
# coding: utf-8
from flask_wtf import Form
from wtforms import StringField, TextAreaField, SelectField, HiddenField
from wtforms.validators import DataRequired, Optional


class TextForm(Form):
    channel_id = SelectField('频道', coerce=int)
    title = StringField('标题', validators=[Optional()], description='选填')
    content = TextAreaField('内容', validators=[DataRequired('内容不能为空')])


class ImageForm(Form):
    channel_id = SelectField('频道', coerce=int)
    image = HiddenField('图片', validators=[DataRequired('图片不能为空')])
    desc = TextAreaField('描述', validators=[Optional()])

application/forms/user.py
# coding: utf-8
from flask_wtf import Form
from wtforms import StringField
from wtforms.validators import DataRequired


class ExampleForm(Form):
    field = StringField('', validators=[DataRequired()])

application/__init__.py
# coding: utf-8
import sys
import os

# Insert project root path to sys.path
project_path = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
if project_path not in sys.path:
    sys.path.insert(0, project_path)

import time
import logging
from flask import Flask, request, url_for, g, render_template
from flask_wtf.csrf import CsrfProtect
from flask.ext.uploads import configure_uploads
from flask_debugtoolbar import DebugToolbarExtension
from werkzeug.wsgi import SharedDataMiddleware
from werkzeug.contrib.fixers import ProxyFix
from six import iteritems
from .utils.account import get_current_user
from config import load_config

# convert python's encoding to utf8
try:
    from imp import reload

    reload(sys)
    sys.setdefaultencoding('utf8')
except (AttributeError, NameError):
    pass


def create_app():
    """Create Flask app."""
    config = load_config()

    if config.DEBUG or config.TESTING:
        app = Flask(__name__)
    else:
        app = Flask(__name__, template_folder=os.path.join(project_path, 'output/templates'))

    app.config.from_object(config)

    if not hasattr(app, 'production'):
        app.production = not app.debug and not app.testing

    # Proxy fix
    app.wsgi_app = ProxyFix(app.wsgi_app)

    # CSRF protect
    CsrfProtect(app)

    # Log errors to stderr in production mode
    if app.production:
        app.logger.addHandler(logging.StreamHandler())
        app.logger.setLevel(logging.ERROR)

        # Enable Sentry
        if app.config.get('SENTRY_DSN'):
            from .utils.sentry import sentry

            sentry.init_app(app, dsn=app.config.get('SENTRY_DSN'))

        # Serve static files during production
        app.wsgi_app = SharedDataMiddleware(app.wsgi_app, {
            '/': os.path.join(project_path, 'output')
        })
    else:
        DebugToolbarExtension(app)

        # Serve static files during development
        app.wsgi_app = SharedDataMiddleware(app.wsgi_app, {
            '/uploads': os.path.join(app.config.get('PROJECT_PATH'), 'uploads')
        })

    # Register components
    register_db(app)
    register_routes(app)
    register_jinja(app)
    register_error_handle(app)
    register_uploadsets(app)
    register_hooks(app)

    return app


def register_jinja(app):
    """Register jinja filters, vars, functions."""
    from .utils import filters, permissions, helpers

    app.jinja_env.filters.update({
        'timesince': filters.timesince
    })

    def url_for_other_page(page):
        """Generate url for pagination."""
        view_args = request.view_args.copy()
        args = request.args.copy().to_dict()
        combined_args = dict(view_args.items() + args.items())
        combined_args['page'] = page
        return url_for(request.endpoint, **combined_args)

    rules = {}
    for endpoint, _rules in iteritems(app.url_map._rules_by_endpoint):
        if any(item in endpoint for item in ['_debug_toolbar', 'debugtoolbar', 'static']):
            continue
        rules[endpoint] = [{'rule': rule.rule} for rule in _rules]

    app.jinja_env.globals.update({
        'absolute_url_for': helpers.absolute_url_for,
        'url_for_other_page': url_for_other_page,
        'rules': rules,
        'permissions': permissions
    })


def register_db(app):
    """Register models."""
    from .models import db

    db.init_app(app)


def register_routes(app):
    """Register routes."""
    from . import controllers
    from flask.blueprints import Blueprint

    for module in _import_submodules_from_package(controllers):
        bp = getattr(module, 'bp')
        if bp and isinstance(bp, Blueprint):
            app.register_blueprint(bp)


def register_error_handle(app):
    """Register HTTP error pages."""

    @app.errorhandler(403)
    def page_403(error):
        return render_template('site/403.html'), 403

    @app.errorhandler(404)
    def page_404(error):
        return render_template('site/404.html'), 404

    @app.errorhandler(500)
    def page_500(error):
        return render_template('site/500.html'), 500


def register_uploadsets(app):
    """Register UploadSets."""
    from .utils.uploadsets import avatars, images

    configure_uploads(app, (avatars, images))


def register_hooks(app):
    """Register hooks."""

    @app.before_request
    def before_request():
        g.user = get_current_user()
        if g.user and g.user.is_admin:
            g._before_request_time = time.time()

    @app.after_request
    def after_request(response):
        if hasattr(g, '_before_request_time'):
            delta = time.time() - g._before_request_time
            response.headers['X-Render-Time'] = delta * 1000
        return response


def _get_template_name(template_reference):
    """Get current template name."""
    return template_reference._TemplateReference__context.name


def _import_submodules_from_package(package):
    import pkgutil

    modules = []
    for importer, modname, ispkg in pkgutil.iter_modules(package.__path__,
                                                         prefix=package.__name__ + "."):
        modules.append(__import__(modname, fromlist="dummy"))
    return modules

application/controllers/account.py
# coding: utf-8
from flask import render_template, Blueprint, redirect, request, url_for
from ..forms import SigninForm, SignupForm
from ..utils.account import signin_user, signout_user
from ..utils.permissions import VisitorPermission, UserPermission
from ..models import db, User

bp = Blueprint('account', __name__)


@bp.route('/signin', methods=['GET', 'POST'])
@VisitorPermission()
def signin():
    """Signin"""
    form = SigninForm()
    if form.validate_on_submit():
        signin_user(form.user)
        return redirect(url_for('site.index'))
    return render_template('account/signin.html', form=form)


@bp.route('/signup', methods=['GET', 'POST'])
@VisitorPermission()
def signup():
    """Signup"""
    form = SignupForm()
    if form.validate_on_submit():
        user = User(**form.data)
        db.session.add(user)
        db.session.commit()
        signin_user(user)
        return redirect(url_for('site.index'))
    return render_template('account/signup.html', form=form)


@bp.route('/signout')
def signout():
    """Signout"""
    signout_user()
    return redirect(request.referrer or url_for('site.index'))

application/controllers/channel.py
# coding: utf-8
from flask import Blueprint, render_template, redirect, url_for, g, request
from ..utils.permissions import UserPermission
from ..forms.channel import ChannelForm
from ..models import db, Channel, Piece
from ..utils.decorators import jsonify
from ..utils.uploadsets import images, process_channel_cover

bp = Blueprint('channel', __name__)


@bp.route('/channel/add', methods=['GET', 'POST'])
@UserPermission()
def add():
    """创建频道"""
    form = ChannelForm()
    if form.validate_on_submit():
        channel = Channel(name=form.name.data, user_id=g.user.id)
        db.session.add(channel)
        db.session.commit()
        return redirect(url_for('.view', uid=channel.id))
    return render_template('channel/add.html', form=form)


@bp.route('/channel/remove', methods=['POST'])
@UserPermission()
def remove():
    """移除频道"""
    pass


@bp.route('/channel/<int:uid>/edit', methods=['GET', 'POST'])
@UserPermission()
def edit(uid):
    """编辑频道"""
    channel = Channel.query.get_or_404(uid)
    form = ChannelForm(obj=channel)
    if form.validate_on_submit():
        # channel.cover = form.cover.data
        channel.name = form.name.data
        db.session.add(channel)
        db.session.commit()
        return redirect(url_for('.view', uid=channel.id))
    return render_template('channel/edit.html', form=form, channel=channel)


@bp.route('/channel/<int:uid>')
def view(uid):
    """频道主页"""
    channel = Channel.query.get_or_404(uid)
    pieces = channel.pieces
    return render_template('channel/view.html', channel=channel, pieces=pieces)


@bp.route('/channel/upload_cover', methods=['POST'])
@UserPermission()
@jsonify
def upload_cover():
    """上传通用图片"""
    try:
        filename = process_channel_cover(request.files['file'])
    except Exception, e:
        return {'result': False, 'error': e.__repr__()}
    else:
        return {'result': True, 'url': images.url(filename), 'path': filename}

application/controllers/piece.py
# coding: utf-8
from flask import Blueprint, render_template, redirect, url_for, g, request
from ..utils.permissions import UserPermission
from ..forms.piece import TextForm, ImageForm
from ..models import db, Piece

bp = Blueprint('piece', __name__)


@bp.route('/piece/add')
@UserPermission()
def add():
    """添加条目"""
    return render_template('piece/add.html')


@bp.route('/piece/add_text', methods=['GET', 'POST'])
@UserPermission()
def add_text():
    """添加文字类条目"""
    channel_id = request.args.get('channel_id', type=int)
    form = TextForm()
    if channel_id:
        form.channel_id.data = channel_id
    form.channel_id.choices = [(c.id, c.name) for c in g.user.channels]
    if form.validate_on_submit():
        piece = Piece(title=form.title.data, content=form.content.data, channel_id=form.channel_id.data,
                      user_id=g.user.id, kind='TEXT')
        db.session.add(piece)
        db.session.commit()
        return redirect(url_for('channel.view', uid=piece.channel_id))
    return render_template('piece/add_text.html', form=form)


@bp.route('/piece/edit_text')
def edit_text():
    """编辑文字类条目"""
    return render_template('piece/edit_text.html')


@bp.route('/piece/add_image', methods=['GET', 'POST'])
@UserPermission()
def add_image():
    """添加图片"""
    channel_id = request.args.get('channel_id', type=int)
    form = ImageForm()
    if channel_id:
        form.channel_id.data = channel_id
    form.channel_id.choices = [(c.id, c.name) for c in g.user.channels]
    if form.validate_on_submit():
        piece = Piece(image=form.image.data, desc=form.desc.data, channel_id=form.channel_id.data, user_id=g.user.id,
                      kind='IMAGE')
        db.session.add(piece)
        db.session.commit()
        return redirect(url_for('channel.view', uid=piece.channel_id))
    return render_template('piece/add_image.html', form=form)


@bp.route('/piece/edit_image')
def edit_image():
    return render_template('piece/edit_image.html')


@bp.route('/piece/<int:uid>')
def view(uid):
    """单个条目"""
    piece = Piece.query.get_or_404(uid)
    return render_template('piece/view.html', piece=piece)


@bp.route('/piece/<int:uid>/edit', methods=['GET', 'POST'])
@UserPermission()
def edit(uid):
    """编辑条目"""
    piece = Piece.query.get_or_404(uid)
    if piece.kind == 'TEXT':
        form = TextForm(obj=piece)
        form.channel_id.choices = [(c.id, c.name) for c in g.user.channels]
        if form.validate_on_submit():
            piece.title = form.title.data
            piece.content = form.content.data
            piece.channel_id = form.channel_id.data
            db.session.add(piece)
            db.session.commit()
            return redirect(url_for('.view', uid=uid))
        return render_template('piece/edit_text.html', form=form)

    elif piece.kind == 'IMAGE':
        form = ImageForm(obj=piece)
        form.channel_id.choices = [(c.id, c.name) for c in g.user.channels]
        if form.validate_on_submit():
            piece.image = form.image.data
            piece.desc = form.desc.data
            piece.channel_id = form.channel_id.data
            db.session.add(piece)
            db.session.commit()
            return redirect(url_for('.view', uid=uid))
        return render_template('piece/edit_image.html', form=form)

application/controllers/site.py
# coding: utf-8
from flask import render_template, Blueprint, request, redirect, url_for, g
from ..utils.permissions import UserPermission
from ..utils.decorators import jsonify
from ..utils.uploadsets import images, process_site_image
from ..models import Channel

bp = Blueprint('site', __name__)


@bp.route('/')
def index():
    """Index page."""
    if not g.user:
        return redirect(url_for('.discover'))
    return render_template('site/index.html')


@bp.route('/about')
def about():
    """About page."""
    return render_template('site/about.html')


@bp.route('/upload_image', methods=['POST'])
@UserPermission()
@jsonify
def upload_image():
    """上传通用图片"""
    try:
        filename = process_site_image(request.files['file'])
    except Exception, e:
        return {'success': False, 'error': e.__repr__()}
    else:
        return {'success': True, 'file_path': images.url(filename)}


@bp.route('/discover')
def discover():
    """发现"""
    channels = Channel.query.limit(30)
    return render_template('site/discover.html', channels=channels)

application/controllers/user.py
# coding: utf-8
from flask import Blueprint, render_template, g
from ..models import Channel, User
from ..utils.permissions import UserPermission

bp = Blueprint('user', __name__)


@bp.route('/my/channels')
@UserPermission()
def channels():
    """我的频道"""
    channels = g.user.channels
    return render_template('user/channels.html', channels=channels)


@bp.route('/people/<int:uid>')
def profile(uid):
    """用户主页"""
    user = User.query.get_or_404(uid)
    channels = user.channels
    return render_template('user/profile.html', user=user, channels=channels)


@bp.route('/people/<int:uid>/channels')
def channels_for_profile(uid):
    """用户频道"""
    user = User.query.get_or_404(uid)
    channels = user.channels
    return render_template('user/channels_for_profile.html', user=user, channels=channels)

application/templates/macros/_channel.html
{% from "macros/_form.html" import vertical_field, field_errors %}


{# 关注频道 #}
{% macro follow_channel_wap(channel, small=False) %}
    <a href="javascript: void(0)"
       class="btn btn-default {% if small %}btn-xs small{% else %}btn-sm{% endif %} mm-follow-channel-wap"
       data-id="{{ channel.id }}">
        <span class="for-follow">关注</span>
        <span class="divider">|</span>
        <span class="followers-count">{{ channel.followers.count() }}</span>
    </a>
{% endmacro %}


{# 添加 & 编辑频道form #}
{% macro channel_form(form, channel=None) %}
    <form action="" method="post" class="mm-channel-form">
        {{ form.csrf_token() }}

        {{ vertical_field(form.name) }}

        {#        <div class="form-group clearfix">#}
        {#            <label for="desc">图标</label>#}
        {##}
        {#            <img src="{{ channel.cover_url or "" if channel else "" }}" alt="">#}
        {#            <input type="file">#}
        {##}
        {#            <div>#}
        {#                <button type="button" class="btn-upload-cover btn btn-default btn-xs">上传图片</button>#}
        {#            </div>#}
        {##}
        {#            {{ form.cover() }}#}
        {#            {{ field_errors(form.cover) }}#}
        {#        </div>#}

        {#        {{ vertical_field(form.tags) }}#}

        <button type="submit" class="btn btn-primary">保存</button>
    </form>

    <script>
        (function () {
            var $form = $('.mm-channel-form');

            $form.find('#name').focus();

            // 上传频道图标
            var uploader = simple.uploader({
                url: urlFor('channel.upload_cover'),
                fileKey: 'file',
                connectionCount: 1,
                'params': {
                    token: g.csrfToken
                }
            });

            $form.on('click', '.btn-upload-cover', function () {
                $form.find("input[type='file']").click();
            });

            $form.on('change', "input[type='file']", function () {
                uploader.upload(this.files);
            });

            uploader.on('uploadsuccess', function (e, file, response) {
                if (response.result) {
                    $form.find('img').attr('src', response.url);
                    $form.find("#cover").val(response.path);
                }
            });
        })();
    </script>
{% endmacro %}


{# 频道 #}
{% macro render_channels(channels) %}
    {% for channel in channels %}
        <div class="mm-channel media" data-href="{{ url_for('channel.view', uid=channel.id) }}">
            <div class="media-left">
                <a href="{{ url_for('user.profile', uid=channel.user_id) }}">
                    <img src="{{ channel.user.avatar_url }}" alt="" class="img-circle channel-creator-avatar">
                </a>
            </div>

            <div class="media-body">
                <a class="name" href="{{ url_for('channel.view', uid=channel.id) }}">{{ channel.name }}</a>

                <div class="meta">
                    <span class="pieces-count">{{ channel.pieces.count() }} 条目</span>

                    {% if not g.user or g.user.id != channel.user_id %}
                        {{ follow_channel_wap(channel, small=True) }}
                    {% endif %}
                </div>
            </div>
        </div>
    {% endfor %}

    <script>
        (function () {
            // 跳转到channel
            $(document).on('click', '.mm-channel', function (e) {
                var href = $(this).data('href');

                if (e.target.tagName !== 'A' && $(e.target).parents('a').length === 0) {
                    window.location = href;
                }
            });
        })();
    </script>
{% endmacro %}

application/templates/macros/_form.html
{% macro field_errors(field) %}
    <ul class="list-form-errors text-danger list-unstyled">
        <li>{{ field.errors[0] }}</li>
    </ul>
{% endmacro %}


{% macro horizontal_field(field, length=6, label=True, static=False) %}
    <div class="form-group clearfix">
        {% if label %}
            {{ field.label(class="col-md-2 control-label") }}
        {% endif %}

        <div class="col-md-{{ length }}
         {% if not label %}col-md-offset-2{% endif %}
         {% if static %}form-control-static{% endif %}">
            {{ field(class="form-control", placeholder=field.description, **kwargs) }}
            {{ field_errors(field) }}
        </div>
    </div>
{% endmacro %}


{% macro checkbox_field(field) %}
    <div class="form-group clearfix">
        <div class="col-md-offset-2 col-sm-10">
            <div class="checkbox">
                {{ field() }}
                {{ field.label() }}
            </div>
        </div>
    </div>
{% endmacro %}


{% macro form_submit(btn_text) %}
    <div class="form-group clearfix">
        <div class="col-sm-6 col-sm-offset-2">
            <button type="submit" class="btn btn-sm btn-primary">{{ btn_text }}</button>
        </div>
    </div>
{% endmacro %}


{% macro vertical_field(field) %}
    <div class="form-group clearfix">
        {{ field.label() }}
        {{ field(class="form-control", placeholder=field.description, **kwargs) }}
        {{ field_errors(field) }}
    </div>
{% endmacro %}

application/templates/macros/_piece.html
{% from "macros/_form.html" import vertical_field, field_errors %}

{# 文字类条目form #}
{% macro text_piece_form(form) %}
    <form action="" method="post" class="mm-text-piece-form">
        {{ form.csrf_token() }}

        {{ vertical_field(form.title) }}

        {{ vertical_field(form.content, rows=10) }}

        {{ vertical_field(form.channel_id) }}

        <button type="submit" class="btn btn-primary">保存</button>
    </form>

    <script>
        var contentEditor = new Simditor({
            textarea: $("textarea[name='content']"),
            toolbar: ['bold', 'italic', 'underline', 'ol', 'ul', 'blockquote', 'code', 'link', 'image', 'markdown'],
            upload: {
                url: urlFor('site.upload_image'),
                fileKey: 'file',
                connectionCount: 1,
                leaveConfirm: '正在上传文件，如果离开上传会自动取消',
                params: {
                    token: g.csrfToken
                }
            }
        });
    </script>
{% endmacro %}


{# 图片类条目form #}
{% macro image_piece_form(form) %}
    <form action="" method="post" class="mm-image-piece-form">
        {{ form.csrf_token() }}

        <div class="form-group clearfix">
            <label for="desc">图片</label>

            <img src="{{ form.image.data or "" }}" alt="">
            <input type="file">

            <div>
                <button type="button" class="btn-upload-image btn btn-default btn-xs">上传图片</button>
            </div>

            {{ form.image() }}
            {{ field_errors(form.image) }}
        </div>

        {{ vertical_field(form.desc) }}

        {{ vertical_field(form.channel_id) }}

        <button type="submit" class="btn btn-primary">保存</button>
    </form>

    <script>
        (function () {
            var $form = $('.mm-image-piece-form');

            // 上传话题图片
            var uploader = simple.uploader({
                url: urlFor('site.upload_image'),
                fileKey: 'file',
                connectionCount: 1,
                'params': {
                    token: g.csrfToken
                }
            });

            $form.on('click', '.btn-upload-image', function () {
                $form.find("input[type='file']").click();
            });

            $form.on('change', "input[type='file']", function () {
                uploader.upload(this.files);
            });

            uploader.on('uploadsuccess', function (e, file, response) {
                if (response.success) {
                    $form.find('img').attr('src', response.file_path);
                    $form.find("#image").val(response.file_path);
                }
            });
        })();
    </script>
{% endmacro %}


{% macro render_piece(piece, with_channel=False) %}
    <div class="mm-piece piece-{{ piece.kind|lower }}">
        {% if piece.kind == 'TEXT' %}
            {% if piece.title %}
                <div class="title">{{ piece.title }}</div>
            {% endif %}

            <div class="details">
                <div>{{ piece.content|safe }}</div>
            </div>

        {% elif piece.kind == 'IMAGE' %}
            <img src="{{ piece.image }}" class="img-responsive" alt="">

            <div class="details">
                <div class="desc">
                    {{ piece.desc }}
                </div>
            </div>
        {% endif %}

        <div class="other">
            {% if with_channel %}
                <a class="channel" href="{{ url_for('channel.view', uid=piece.channel_id) }}">
                    {{ piece.channel.name }}</a>
            {% endif %}

            <span class="time">{{ piece.created_at|timesince }}</span>

            {% if g.user and g.user.id == piece.user_id %}
                <span class="commands">
                    <a class="btn-edit" href="{{ url_for('piece.edit', uid=piece.id) }}">编辑</a>
                </span>
            {% endif %}
        </div>
    </div>
{% endmacro %}


{% macro render_pieces(pieces, with_channel=False) %}
    {% for piece in pieces %}
        {{ render_piece(piece, with_channel=with_channel) }}
    {% endfor %}
{% endmacro %}

application/templates/macros/_utils.html
{% macro pagination(paginator) %}
    {% if paginator.pages > 1 %}
        <ul class='pagination pagination-sm'>
            {% if paginator.has_prev %}
                <li><a href="{{ url_for_other_page(paginator.prev_num) }}">上一页</a></li>
            {% endif %}

            {% for page in paginator.iter_pages() %}
                {% if page %}
                    {% if page != paginator.page %}
                        <li><a href="{{ url_for_other_page(page) }}">{{ page }}</a></li>
                    {% else %}
                        <li class="active"><span>{{ page }}</span></li>
                    {% endif %}
                {% else %}
                    <li class="ellipsis"><span>...</span></li>
                {% endif %}
            {% endfor %}

            {% if paginator.has_next %}
                <li><a href="{{ url_for_other_page(paginator.next_num) }}">下一页</a></li>
            {% endif %}
        </ul>
    {% endif %}
{% endmacro %}